sonar.projectKey=franjofranjic27_finyo-fe
sonar.organization=franjofranjic27
sonar.projectName=finyo-fe

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/vite-env.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/main.tsx,src/components/ui/**
